// Atlas service definitions — gRPC feature parity with the REST API
// (docs/api.md). Timestamps are RFC 3339 strings, matching the JSON API.
//
// Regenerate with: make proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: atlas.proto

package atlaspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_atlas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{0}
}

func (x *Endpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Endpoint) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	RealmId       string                 `protobuf:"bytes,5,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	ShardId       string                 `protobuf:"bytes,6,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Platform      string                 `protobuf:"bytes,8,opt,name=platform,proto3" json:"platform,omitempty"`
	Endpoint      *Endpoint              `protobuf:"bytes,9,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Capacity      int32                  `protobuf:"varint,10,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	Players       int32                  `protobuf:"varint,13,opt,name=players,proto3" json:"players,omitempty"`
	Load          float64                `protobuf:"fixed64,14,opt,name=load,proto3" json:"load,omitempty"`
	LastSeenAt    string                 `protobuf:"bytes,15,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_atlas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Server) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Server) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *Server) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *Server) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Server) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Server) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *Server) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Server) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Server) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Server) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

func (x *Server) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *Server) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *Server) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Server) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Character struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CharacterId   int64                  `protobuf:"varint,3,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	ClassId       int32                  `protobuf:"varint,6,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastLoginAt   string                 `protobuf:"bytes,9,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_atlas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{2}
}

func (x *Character) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Character) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Character) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Character) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *Character) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Character) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Character) GetLastLoginAt() string {
	if x != nil {
		return x.LastLoginAt
	}
	return ""
}

func (x *Character) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Character) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	RealmId       string                 `protobuf:"bytes,5,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	ShardId       string                 `protobuf:"bytes,6,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Platform      string                 `protobuf:"bytes,8,opt,name=platform,proto3" json:"platform,omitempty"`
	Endpoint      *Endpoint              `protobuf:"bytes,9,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Capacity      int32                  `protobuf:"varint,10,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_atlas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RegisterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *RegisterRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterRequest) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *RegisterRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_atlas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Players       int32                  `protobuf:"varint,2,opt,name=players,proto3" json:"players,omitempty"`
	Load          float64                `protobuf:"fixed64,3,opt,name=load,proto3" json:"load,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_atlas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *HeartbeatRequest) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

func (x *HeartbeatRequest) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerId        string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	NextHeartbeatIn int32                  `protobuf:"varint,3,opt,name=next_heartbeat_in,json=nextHeartbeatIn,proto3" json:"next_heartbeat_in,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_atlas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatResponse) GetNextHeartbeatIn() int32 {
	if x != nil {
		return x.NextHeartbeatIn
	}
	return 0
}

type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_atlas_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{7}
}

func (x *UnregisterRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_atlas_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{8}
}

func (x *UnregisterResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UnregisterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Realm         string                 `protobuf:"bytes,3,opt,name=realm,proto3" json:"realm,omitempty"`
	Shard         string                 `protobuf:"bytes,4,opt,name=shard,proto3" json:"shard,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Platform      string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,8,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersRequest) Reset() {
	*x = ListServersRequest{}
	mi := &file_atlas_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersRequest) ProtoMessage() {}

func (x *ListServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersRequest.ProtoReflect.Descriptor instead.
func (*ListServersRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{9}
}

func (x *ListServersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListServersRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ListServersRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *ListServersRequest) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *ListServersRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ListServersRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ListServersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListServersRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*Server              `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersResponse) Reset() {
	*x = ListServersResponse{}
	mi := &file_atlas_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersResponse) ProtoMessage() {}

func (x *ListServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersResponse.ProtoReflect.Descriptor instead.
func (*ListServersResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{10}
}

func (x *ListServersResponse) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

type GetServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerRequest) Reset() {
	*x = GetServerRequest{}
	mi := &file_atlas_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRequest) ProtoMessage() {}

func (x *GetServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRequest.ProtoReflect.Descriptor instead.
func (*GetServerRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{11}
}

func (x *GetServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type GetServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerResponse) Reset() {
	*x = GetServerResponse{}
	mi := &file_atlas_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerResponse) ProtoMessage() {}

func (x *GetServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerResponse.ProtoReflect.Descriptor instead.
func (*GetServerResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{12}
}

func (x *GetServerResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type CreateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CharacterId   int64                  `protobuf:"varint,3,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	ClassId       int32                  `protobuf:"varint,6,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterRequest) Reset() {
	*x = CreateCharacterRequest{}
	mi := &file_atlas_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterRequest) ProtoMessage() {}

func (x *CreateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterRequest.ProtoReflect.Descriptor instead.
func (*CreateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCharacterRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateCharacterRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateCharacterRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CreateCharacterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCharacterRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateCharacterRequest) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

type CreateCharacterResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Character *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	// "created" on the synchronous adapter, "queued" on asynchronous ones.
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterResponse) Reset() {
	*x = CreateCharacterResponse{}
	mi := &file_atlas_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterResponse) ProtoMessage() {}

func (x *CreateCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterResponse.ProtoReflect.Descriptor instead.
func (*CreateCharacterResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{14}
}

func (x *CreateCharacterResponse) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

func (x *CreateCharacterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterRequest) Reset() {
	*x = GetCharacterRequest{}
	mi := &file_atlas_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterRequest) ProtoMessage() {}

func (x *GetCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{15}
}

func (x *GetCharacterRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type GetCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterResponse) Reset() {
	*x = GetCharacterResponse{}
	mi := &file_atlas_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterResponse) ProtoMessage() {}

func (x *GetCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterResponse.ProtoReflect.Descriptor instead.
func (*GetCharacterResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{16}
}

func (x *GetCharacterResponse) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type ListCharactersByAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersByAccountRequest) Reset() {
	*x = ListCharactersByAccountRequest{}
	mi := &file_atlas_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersByAccountRequest) ProtoMessage() {}

func (x *ListCharactersByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersByAccountRequest.ProtoReflect.Descriptor instead.
func (*ListCharactersByAccountRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{17}
}

func (x *ListCharactersByAccountRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type ListCharactersByAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*Character           `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersByAccountResponse) Reset() {
	*x = ListCharactersByAccountResponse{}
	mi := &file_atlas_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersByAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersByAccountResponse) ProtoMessage() {}

func (x *ListCharactersByAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersByAccountResponse.ProtoReflect.Descriptor instead.
func (*ListCharactersByAccountResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{18}
}

func (x *ListCharactersByAccountResponse) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

type ListCharactersByServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersByServerRequest) Reset() {
	*x = ListCharactersByServerRequest{}
	mi := &file_atlas_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersByServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersByServerRequest) ProtoMessage() {}

func (x *ListCharactersByServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersByServerRequest.ProtoReflect.Descriptor instead.
func (*ListCharactersByServerRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{19}
}

func (x *ListCharactersByServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListCharactersByServerRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCharactersByServerRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListCharactersByServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*Character           `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersByServerResponse) Reset() {
	*x = ListCharactersByServerResponse{}
	mi := &file_atlas_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersByServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersByServerResponse) ProtoMessage() {}

func (x *ListCharactersByServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersByServerResponse.ProtoReflect.Descriptor instead.
func (*ListCharactersByServerResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{20}
}

func (x *ListCharactersByServerResponse) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *ListCharactersByServerResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// UpdateCharacterRequest: absent (default) fields mean "no change",
// matching the JSON PATCH semantics.
type UpdateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CharacterId   int64                  `protobuf:"varint,3,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Level         *int32                 `protobuf:"varint,5,opt,name=level,proto3,oneof" json:"level,omitempty"`
	ClassId       *int32                 `protobuf:"varint,6,opt,name=class_id,json=classId,proto3,oneof" json:"class_id,omitempty"`
	Avatar        *string                `protobuf:"bytes,7,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCharacterRequest) Reset() {
	*x = UpdateCharacterRequest{}
	mi := &file_atlas_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCharacterRequest) ProtoMessage() {}

func (x *UpdateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCharacterRequest.ProtoReflect.Descriptor instead.
func (*UpdateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateCharacterRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateCharacterRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdateCharacterRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *UpdateCharacterRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateCharacterRequest) GetLevel() int32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *UpdateCharacterRequest) GetClassId() int32 {
	if x != nil && x.ClassId != nil {
		return *x.ClassId
	}
	return 0
}

func (x *UpdateCharacterRequest) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

type UpdateCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCharacterResponse) Reset() {
	*x = UpdateCharacterResponse{}
	mi := &file_atlas_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCharacterResponse) ProtoMessage() {}

func (x *UpdateCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCharacterResponse.ProtoReflect.Descriptor instead.
func (*UpdateCharacterResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateCharacterResponse) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

func (x *UpdateCharacterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterRequest) Reset() {
	*x = DeleteCharacterRequest{}
	mi := &file_atlas_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterRequest) ProtoMessage() {}

func (x *DeleteCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterRequest.ProtoReflect.Descriptor instead.
func (*DeleteCharacterRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteCharacterRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type DeleteCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterResponse) Reset() {
	*x = DeleteCharacterResponse{}
	mi := &file_atlas_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterResponse) ProtoMessage() {}

func (x *DeleteCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterResponse.ProtoReflect.Descriptor instead.
func (*DeleteCharacterResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteCharacterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RecommendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_atlas_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{25}
}

func (x *RecommendRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *RecommendRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RecommendRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RecommendRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RecommendRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RecommendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_atlas_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{26}
}

func (x *RecommendResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *RecommendResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ServerIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerIdRequest) Reset() {
	*x = ServerIdRequest{}
	mi := &file_atlas_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerIdRequest) ProtoMessage() {}

func (x *ServerIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerIdRequest.ProtoReflect.Descriptor instead.
func (*ServerIdRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{27}
}

func (x *ServerIdRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type OkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OkResponse) Reset() {
	*x = OkResponse{}
	mi := &file_atlas_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResponse) ProtoMessage() {}

func (x *OkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResponse.ProtoReflect.Descriptor instead.
func (*OkResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{28}
}

func (x *OkResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *OkResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_atlas_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{29}
}

type GetStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalServers     int32                  `protobuf:"varint,1,opt,name=total_servers,json=totalServers,proto3" json:"total_servers,omitempty"`
	ServersByStatus  map[string]int32       `protobuf:"bytes,2,rep,name=servers_by_status,json=serversByStatus,proto3" json:"servers_by_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ServersByRegion  map[string]int32       `protobuf:"bytes,3,rep,name=servers_by_region,json=serversByRegion,proto3" json:"servers_by_region,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ServersByVersion map[string]int32       `protobuf:"bytes,4,rep,name=servers_by_version,json=serversByVersion,proto3" json:"servers_by_version,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TotalPlayers     int32                  `protobuf:"varint,5,opt,name=total_players,json=totalPlayers,proto3" json:"total_players,omitempty"`
	TotalCapacity    int32                  `protobuf:"varint,6,opt,name=total_capacity,json=totalCapacity,proto3" json:"total_capacity,omitempty"`
	TotalCharacters  int32                  `protobuf:"varint,7,opt,name=total_characters,json=totalCharacters,proto3" json:"total_characters,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_atlas_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{30}
}

func (x *GetStatsResponse) GetTotalServers() int32 {
	if x != nil {
		return x.TotalServers
	}
	return 0
}

func (x *GetStatsResponse) GetServersByStatus() map[string]int32 {
	if x != nil {
		return x.ServersByStatus
	}
	return nil
}

func (x *GetStatsResponse) GetServersByRegion() map[string]int32 {
	if x != nil {
		return x.ServersByRegion
	}
	return nil
}

func (x *GetStatsResponse) GetServersByVersion() map[string]int32 {
	if x != nil {
		return x.ServersByVersion
	}
	return nil
}

func (x *GetStatsResponse) GetTotalPlayers() int32 {
	if x != nil {
		return x.TotalPlayers
	}
	return 0
}

func (x *GetStatsResponse) GetTotalCapacity() int32 {
	if x != nil {
		return x.TotalCapacity
	}
	return 0
}

func (x *GetStatsResponse) GetTotalCharacters() int32 {
	if x != nil {
		return x.TotalCharacters
	}
	return 0
}

type SearchCharactersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ClassId       *int32                 `protobuf:"varint,3,opt,name=class_id,json=classId,proto3,oneof" json:"class_id,omitempty"`
	MinLevel      *int32                 `protobuf:"varint,4,opt,name=min_level,json=minLevel,proto3,oneof" json:"min_level,omitempty"`
	MaxLevel      *int32                 `protobuf:"varint,5,opt,name=max_level,json=maxLevel,proto3,oneof" json:"max_level,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,7,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCharactersRequest) Reset() {
	*x = SearchCharactersRequest{}
	mi := &file_atlas_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCharactersRequest) ProtoMessage() {}

func (x *SearchCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCharactersRequest.ProtoReflect.Descriptor instead.
func (*SearchCharactersRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{31}
}

func (x *SearchCharactersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchCharactersRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *SearchCharactersRequest) GetClassId() int32 {
	if x != nil && x.ClassId != nil {
		return *x.ClassId
	}
	return 0
}

func (x *SearchCharactersRequest) GetMinLevel() int32 {
	if x != nil && x.MinLevel != nil {
		return *x.MinLevel
	}
	return 0
}

func (x *SearchCharactersRequest) GetMaxLevel() int32 {
	if x != nil && x.MaxLevel != nil {
		return *x.MaxLevel
	}
	return 0
}

func (x *SearchCharactersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchCharactersRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type SearchCharactersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*Character           `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCharactersResponse) Reset() {
	*x = SearchCharactersResponse{}
	mi := &file_atlas_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCharactersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCharactersResponse) ProtoMessage() {}

func (x *SearchCharactersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCharactersResponse.ProtoReflect.Descriptor instead.
func (*SearchCharactersResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{32}
}

func (x *SearchCharactersResponse) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *SearchCharactersResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type Migration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceServers []string               `protobuf:"bytes,2,rep,name=source_servers,json=sourceServers,proto3" json:"source_servers,omitempty"`
	TargetServer  string                 `protobuf:"bytes,3,opt,name=target_server,json=targetServer,proto3" json:"target_server,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Migration) Reset() {
	*x = Migration{}
	mi := &file_atlas_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Migration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration) ProtoMessage() {}

func (x *Migration) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration.ProtoReflect.Descriptor instead.
func (*Migration) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{33}
}

func (x *Migration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Migration) GetSourceServers() []string {
	if x != nil {
		return x.SourceServers
	}
	return nil
}

func (x *Migration) GetTargetServer() string {
	if x != nil {
		return x.TargetServer
	}
	return ""
}

func (x *Migration) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Migration) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Migration) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

type CreateMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceServers []string               `protobuf:"bytes,1,rep,name=source_servers,json=sourceServers,proto3" json:"source_servers,omitempty"`
	TargetServer  string                 `protobuf:"bytes,2,opt,name=target_server,json=targetServer,proto3" json:"target_server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMigrationRequest) Reset() {
	*x = CreateMigrationRequest{}
	mi := &file_atlas_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMigrationRequest) ProtoMessage() {}

func (x *CreateMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMigrationRequest.ProtoReflect.Descriptor instead.
func (*CreateMigrationRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{34}
}

func (x *CreateMigrationRequest) GetSourceServers() []string {
	if x != nil {
		return x.SourceServers
	}
	return nil
}

func (x *CreateMigrationRequest) GetTargetServer() string {
	if x != nil {
		return x.TargetServer
	}
	return ""
}

type CreateMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migration     *Migration             `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMigrationResponse) Reset() {
	*x = CreateMigrationResponse{}
	mi := &file_atlas_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMigrationResponse) ProtoMessage() {}

func (x *CreateMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMigrationResponse.ProtoReflect.Descriptor instead.
func (*CreateMigrationResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{35}
}

func (x *CreateMigrationResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

type GetMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   string                 `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationRequest) Reset() {
	*x = GetMigrationRequest{}
	mi := &file_atlas_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationRequest) ProtoMessage() {}

func (x *GetMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationRequest.ProtoReflect.Descriptor instead.
func (*GetMigrationRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{36}
}

func (x *GetMigrationRequest) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

type GetMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migration     *Migration             `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationResponse) Reset() {
	*x = GetMigrationResponse{}
	mi := &file_atlas_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationResponse) ProtoMessage() {}

func (x *GetMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationResponse.ProtoReflect.Descriptor instead.
func (*GetMigrationResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{37}
}

func (x *GetMigrationResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

type ListMigrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMigrationsRequest) Reset() {
	*x = ListMigrationsRequest{}
	mi := &file_atlas_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMigrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMigrationsRequest) ProtoMessage() {}

func (x *ListMigrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMigrationsRequest.ProtoReflect.Descriptor instead.
func (*ListMigrationsRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{38}
}

func (x *ListMigrationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMigrationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migrations    []*Migration           `protobuf:"bytes,1,rep,name=migrations,proto3" json:"migrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMigrationsResponse) Reset() {
	*x = ListMigrationsResponse{}
	mi := &file_atlas_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMigrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMigrationsResponse) ProtoMessage() {}

func (x *ListMigrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMigrationsResponse.ProtoReflect.Descriptor instead.
func (*ListMigrationsResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{39}
}

func (x *ListMigrationsResponse) GetMigrations() []*Migration {
	if x != nil {
		return x.Migrations
	}
	return nil
}

type RollbackMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   string                 `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackMigrationRequest) Reset() {
	*x = RollbackMigrationRequest{}
	mi := &file_atlas_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackMigrationRequest) ProtoMessage() {}

func (x *RollbackMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackMigrationRequest.ProtoReflect.Descriptor instead.
func (*RollbackMigrationRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{40}
}

func (x *RollbackMigrationRequest) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

type RollbackMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Migration     *Migration             `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackMigrationResponse) Reset() {
	*x = RollbackMigrationResponse{}
	mi := &file_atlas_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackMigrationResponse) ProtoMessage() {}

func (x *RollbackMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackMigrationResponse.ProtoReflect.Descriptor instead.
func (*RollbackMigrationResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{41}
}

func (x *RollbackMigrationResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

var File_atlas_proto protoreflect.FileDescriptor

const file_atlas_proto_rawDesc = "" +
	"\n" +
	"\vatlas.proto\x12\batlas.v1\"2\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"\xaf\x04\n" +
	"\x06Server\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x19\n" +
	"\brealm_id\x18\x05 \x01(\tR\arealmId\x12\x19\n" +
	"\bshard_id\x18\x06 \x01(\tR\ashardId\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12\x1a\n" +
	"\bplatform\x18\b \x01(\tR\bplatform\x12.\n" +
	"\bendpoint\x18\t \x01(\v2\x12.atlas.v1.EndpointR\bendpoint\x12\x1a\n" +
	"\bcapacity\x18\n" +
	" \x01(\x05R\bcapacity\x12:\n" +
	"\bmetadata\x18\v \x03(\v2\x1e.atlas.v1.Server.MetadataEntryR\bmetadata\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12\x18\n" +
	"\aplayers\x18\r \x01(\x05R\aplayers\x12\x12\n" +
	"\x04load\x18\x0e \x01(\x01R\x04load\x12 \n" +
	"\flast_seen_at\x18\x0f \x01(\tR\n" +
	"lastSeenAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\tR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x03\n" +
	"\tCharacter\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12!\n" +
	"\fcharacter_id\x18\x03 \x01(\x03R\vcharacterId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x19\n" +
	"\bclass_id\x18\x06 \x01(\x05R\aclassId\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12=\n" +
	"\bmetadata\x18\b \x03(\v2!.atlas.v1.Character.MetadataEntryR\bmetadata\x12\"\n" +
	"\rlast_login_at\x18\t \x01(\tR\vlastLoginAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x02\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x19\n" +
	"\brealm_id\x18\x05 \x01(\tR\arealmId\x12\x19\n" +
	"\bshard_id\x18\x06 \x01(\tR\ashardId\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12\x1a\n" +
	"\bplatform\x18\b \x01(\tR\bplatform\x12.\n" +
	"\bendpoint\x18\t \x01(\v2\x12.atlas.v1.EndpointR\bendpoint\x12\x1a\n" +
	"\bcapacity\x18\n" +
	" \x01(\x05R\bcapacity\"<\n" +
	"\x10RegisterResponse\x12(\n" +
	"\x06server\x18\x01 \x01(\v2\x10.atlas.v1.ServerR\x06server\"u\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x18\n" +
	"\aplayers\x18\x02 \x01(\x05R\aplayers\x12\x12\n" +
	"\x04load\x18\x03 \x01(\x01R\x04load\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"t\n" +
	"\x11HeartbeatResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12*\n" +
	"\x11next_heartbeat_in\x18\x03 \x01(\x05R\x0fnextHeartbeatIn\"0\n" +
	"\x11UnregisterRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"I\n" +
	"\x12UnregisterResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xd4\x01\n" +
	"\x12ListServersRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x14\n" +
	"\x05realm\x18\x03 \x01(\tR\x05realm\x12\x14\n" +
	"\x05shard\x18\x04 \x01(\tR\x05shard\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\b \x01(\tR\x06cursor\"A\n" +
	"\x13ListServersResponse\x12*\n" +
	"\aservers\x18\x01 \x03(\v2\x10.atlas.v1.ServerR\aservers\"/\n" +
	"\x10GetServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"=\n" +
	"\x11GetServerResponse\x12(\n" +
	"\x06server\x18\x01 \x01(\v2\x10.atlas.v1.ServerR\x06server\"\xbc\x01\n" +
	"\x16CreateCharacterRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12!\n" +
	"\fcharacter_id\x18\x03 \x01(\x03R\vcharacterId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x19\n" +
	"\bclass_id\x18\x06 \x01(\x05R\aclassId\"d\n" +
	"\x17CreateCharacterResponse\x121\n" +
	"\tcharacter\x18\x01 \x01(\v2\x13.atlas.v1.CharacterR\tcharacter\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"8\n" +
	"\x13GetCharacterRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\"I\n" +
	"\x14GetCharacterResponse\x121\n" +
	"\tcharacter\x18\x01 \x01(\v2\x13.atlas.v1.CharacterR\tcharacter\"?\n" +
	"\x1eListCharactersByAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\"V\n" +
	"\x1fListCharactersByAccountResponse\x123\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x13.atlas.v1.CharacterR\n" +
	"characters\"j\n" +
	"\x1dListCharactersByServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"v\n" +
	"\x1eListCharactersByServerResponse\x123\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x13.atlas.v1.CharacterR\n" +
	"characters\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\x93\x02\n" +
	"\x16UpdateCharacterRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12!\n" +
	"\fcharacter_id\x18\x03 \x01(\x03R\vcharacterId\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05level\x18\x05 \x01(\x05H\x01R\x05level\x88\x01\x01\x12\x1e\n" +
	"\bclass_id\x18\x06 \x01(\x05H\x02R\aclassId\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\a \x01(\tH\x03R\x06avatar\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_levelB\v\n" +
	"\t_class_idB\t\n" +
	"\a_avatar\"d\n" +
	"\x17UpdateCharacterResponse\x121\n" +
	"\tcharacter\x18\x01 \x01(\v2\x13.atlas.v1.CharacterR\tcharacter\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\";\n" +
	"\x16DeleteCharacterRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\"1\n" +
	"\x17DeleteCharacterResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x97\x01\n" +
	"\x10RecommendRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"U\n" +
	"\x11RecommendResponse\x12(\n" +
	"\x06server\x18\x01 \x01(\v2\x10.atlas.v1.ServerR\x06server\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\".\n" +
	"\x0fServerIdRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"A\n" +
	"\n" +
	"OkResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x11\n" +
	"\x0fGetStatsRequest\"\x95\x05\n" +
	"\x10GetStatsResponse\x12#\n" +
	"\rtotal_servers\x18\x01 \x01(\x05R\ftotalServers\x12[\n" +
	"\x11servers_by_status\x18\x02 \x03(\v2/.atlas.v1.GetStatsResponse.ServersByStatusEntryR\x0fserversByStatus\x12[\n" +
	"\x11servers_by_region\x18\x03 \x03(\v2/.atlas.v1.GetStatsResponse.ServersByRegionEntryR\x0fserversByRegion\x12^\n" +
	"\x12servers_by_version\x18\x04 \x03(\v20.atlas.v1.GetStatsResponse.ServersByVersionEntryR\x10serversByVersion\x12#\n" +
	"\rtotal_players\x18\x05 \x01(\x05R\ftotalPlayers\x12%\n" +
	"\x0etotal_capacity\x18\x06 \x01(\x05R\rtotalCapacity\x12)\n" +
	"\x10total_characters\x18\a \x01(\x05R\x0ftotalCharacters\x1aB\n" +
	"\x14ServersByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aB\n" +
	"\x14ServersByRegionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aC\n" +
	"\x15ServersByVersionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x85\x02\n" +
	"\x17SearchCharactersRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x1e\n" +
	"\bclass_id\x18\x03 \x01(\x05H\x00R\aclassId\x88\x01\x01\x12 \n" +
	"\tmin_level\x18\x04 \x01(\x05H\x01R\bminLevel\x88\x01\x01\x12 \n" +
	"\tmax_level\x18\x05 \x01(\x05H\x02R\bmaxLevel\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\a \x01(\tR\x06cursorB\v\n" +
	"\t_class_idB\f\n" +
	"\n" +
	"_min_levelB\f\n" +
	"\n" +
	"_max_level\"p\n" +
	"\x18SearchCharactersResponse\x123\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x13.atlas.v1.CharacterR\n" +
	"characters\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\xc1\x01\n" +
	"\tMigration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0esource_servers\x18\x02 \x03(\tR\rsourceServers\x12#\n" +
	"\rtarget_server\x18\x03 \x01(\tR\ftargetServer\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x06 \x01(\tR\vcompletedAt\"d\n" +
	"\x16CreateMigrationRequest\x12%\n" +
	"\x0esource_servers\x18\x01 \x03(\tR\rsourceServers\x12#\n" +
	"\rtarget_server\x18\x02 \x01(\tR\ftargetServer\"L\n" +
	"\x17CreateMigrationResponse\x121\n" +
	"\tmigration\x18\x01 \x01(\v2\x13.atlas.v1.MigrationR\tmigration\"8\n" +
	"\x13GetMigrationRequest\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\tR\vmigrationId\"I\n" +
	"\x14GetMigrationResponse\x121\n" +
	"\tmigration\x18\x01 \x01(\v2\x13.atlas.v1.MigrationR\tmigration\"-\n" +
	"\x15ListMigrationsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"M\n" +
	"\x16ListMigrationsResponse\x123\n" +
	"\n" +
	"migrations\x18\x01 \x03(\v2\x13.atlas.v1.MigrationR\n" +
	"migrations\"=\n" +
	"\x18RollbackMigrationRequest\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\tR\vmigrationId\"N\n" +
	"\x19RollbackMigrationResponse\x121\n" +
	"\tmigration\x18\x01 \x01(\v2\x13.atlas.v1.MigrationR\tmigration2\xe3\x01\n" +
	"\x0fRegistryService\x12A\n" +
	"\bRegister\x12\x19.atlas.v1.RegisterRequest\x1a\x1a.atlas.v1.RegisterResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.atlas.v1.HeartbeatRequest\x1a\x1b.atlas.v1.HeartbeatResponse\x12G\n" +
	"\n" +
	"Unregister\x12\x1b.atlas.v1.UnregisterRequest\x1a\x1c.atlas.v1.UnregisterResponse2\xa4\x01\n" +
	"\x10DiscoveryService\x12J\n" +
	"\vListServers\x12\x1c.atlas.v1.ListServersRequest\x1a\x1d.atlas.v1.ListServersResponse\x12D\n" +
	"\tGetServer\x12\x1a.atlas.v1.GetServerRequest\x1a\x1b.atlas.v1.GetServerResponse2\xc6\x04\n" +
	"\x10DirectoryService\x12V\n" +
	"\x0fCreateCharacter\x12 .atlas.v1.CreateCharacterRequest\x1a!.atlas.v1.CreateCharacterResponse\x12M\n" +
	"\fGetCharacter\x12\x1d.atlas.v1.GetCharacterRequest\x1a\x1e.atlas.v1.GetCharacterResponse\x12n\n" +
	"\x17ListCharactersByAccount\x12(.atlas.v1.ListCharactersByAccountRequest\x1a).atlas.v1.ListCharactersByAccountResponse\x12k\n" +
	"\x16ListCharactersByServer\x12'.atlas.v1.ListCharactersByServerRequest\x1a(.atlas.v1.ListCharactersByServerResponse\x12V\n" +
	"\x0fUpdateCharacter\x12 .atlas.v1.UpdateCharacterRequest\x1a!.atlas.v1.UpdateCharacterResponse\x12V\n" +
	"\x0fDeleteCharacter\x12 .atlas.v1.DeleteCharacterRequest\x1a!.atlas.v1.DeleteCharacterResponse2V\n" +
	"\x0eRoutingService\x12D\n" +
	"\tRecommend\x12\x1a.atlas.v1.RecommendRequest\x1a\x1b.atlas.v1.RecommendResponse2\xfd\x05\n" +
	"\fAdminService\x12A\n" +
	"\x0eSetMaintenance\x12\x19.atlas.v1.ServerIdRequest\x1a\x14.atlas.v1.OkResponse\x12;\n" +
	"\bSetDrain\x12\x19.atlas.v1.ServerIdRequest\x1a\x14.atlas.v1.OkResponse\x129\n" +
	"\x06Enable\x12\x19.atlas.v1.ServerIdRequest\x1a\x14.atlas.v1.OkResponse\x12:\n" +
	"\aDisable\x12\x19.atlas.v1.ServerIdRequest\x1a\x14.atlas.v1.OkResponse\x12A\n" +
	"\bGetStats\x12\x19.atlas.v1.GetStatsRequest\x1a\x1a.atlas.v1.GetStatsResponse\x12Y\n" +
	"\x10SearchCharacters\x12!.atlas.v1.SearchCharactersRequest\x1a\".atlas.v1.SearchCharactersResponse\x12V\n" +
	"\x0fCreateMigration\x12 .atlas.v1.CreateMigrationRequest\x1a!.atlas.v1.CreateMigrationResponse\x12M\n" +
	"\fGetMigration\x12\x1d.atlas.v1.GetMigrationRequest\x1a\x1e.atlas.v1.GetMigrationResponse\x12S\n" +
	"\x0eListMigrations\x12\x1f.atlas.v1.ListMigrationsRequest\x1a .atlas.v1.ListMigrationsResponse\x12\\\n" +
	"\x11RollbackMigration\x12\".atlas.v1.RollbackMigrationRequest\x1a#.atlas.v1.RollbackMigrationResponseB*Z(github.com/cuihairu/atlas/api/pb;atlaspbb\x06proto3"

var (
	file_atlas_proto_rawDescOnce sync.Once
	file_atlas_proto_rawDescData []byte
)

func file_atlas_proto_rawDescGZIP() []byte {
	file_atlas_proto_rawDescOnce.Do(func() {
		file_atlas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atlas_proto_rawDesc), len(file_atlas_proto_rawDesc)))
	})
	return file_atlas_proto_rawDescData
}

var file_atlas_proto_msgTypes = make([]protoimpl.MessageInfo, 47)
var file_atlas_proto_goTypes = []any{
	(*Endpoint)(nil),                        // 0: atlas.v1.Endpoint
	(*Server)(nil),                          // 1: atlas.v1.Server
	(*Character)(nil),                       // 2: atlas.v1.Character
	(*RegisterRequest)(nil),                 // 3: atlas.v1.RegisterRequest
	(*RegisterResponse)(nil),                // 4: atlas.v1.RegisterResponse
	(*HeartbeatRequest)(nil),                // 5: atlas.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),               // 6: atlas.v1.HeartbeatResponse
	(*UnregisterRequest)(nil),               // 7: atlas.v1.UnregisterRequest
	(*UnregisterResponse)(nil),              // 8: atlas.v1.UnregisterResponse
	(*ListServersRequest)(nil),              // 9: atlas.v1.ListServersRequest
	(*ListServersResponse)(nil),             // 10: atlas.v1.ListServersResponse
	(*GetServerRequest)(nil),                // 11: atlas.v1.GetServerRequest
	(*GetServerResponse)(nil),               // 12: atlas.v1.GetServerResponse
	(*CreateCharacterRequest)(nil),          // 13: atlas.v1.CreateCharacterRequest
	(*CreateCharacterResponse)(nil),         // 14: atlas.v1.CreateCharacterResponse
	(*GetCharacterRequest)(nil),             // 15: atlas.v1.GetCharacterRequest
	(*GetCharacterResponse)(nil),            // 16: atlas.v1.GetCharacterResponse
	(*ListCharactersByAccountRequest)(nil),  // 17: atlas.v1.ListCharactersByAccountRequest
	(*ListCharactersByAccountResponse)(nil), // 18: atlas.v1.ListCharactersByAccountResponse
	(*ListCharactersByServerRequest)(nil),   // 19: atlas.v1.ListCharactersByServerRequest
	(*ListCharactersByServerResponse)(nil),  // 20: atlas.v1.ListCharactersByServerResponse
	(*UpdateCharacterRequest)(nil),          // 21: atlas.v1.UpdateCharacterRequest
	(*UpdateCharacterResponse)(nil),         // 22: atlas.v1.UpdateCharacterResponse
	(*DeleteCharacterRequest)(nil),          // 23: atlas.v1.DeleteCharacterRequest
	(*DeleteCharacterResponse)(nil),         // 24: atlas.v1.DeleteCharacterResponse
	(*RecommendRequest)(nil),                // 25: atlas.v1.RecommendRequest
	(*RecommendResponse)(nil),               // 26: atlas.v1.RecommendResponse
	(*ServerIdRequest)(nil),                 // 27: atlas.v1.ServerIdRequest
	(*OkResponse)(nil),                      // 28: atlas.v1.OkResponse
	(*GetStatsRequest)(nil),                 // 29: atlas.v1.GetStatsRequest
	(*GetStatsResponse)(nil),                // 30: atlas.v1.GetStatsResponse
	(*SearchCharactersRequest)(nil),         // 31: atlas.v1.SearchCharactersRequest
	(*SearchCharactersResponse)(nil),        // 32: atlas.v1.SearchCharactersResponse
	(*Migration)(nil),                       // 33: atlas.v1.Migration
	(*CreateMigrationRequest)(nil),          // 34: atlas.v1.CreateMigrationRequest
	(*CreateMigrationResponse)(nil),         // 35: atlas.v1.CreateMigrationResponse
	(*GetMigrationRequest)(nil),             // 36: atlas.v1.GetMigrationRequest
	(*GetMigrationResponse)(nil),            // 37: atlas.v1.GetMigrationResponse
	(*ListMigrationsRequest)(nil),           // 38: atlas.v1.ListMigrationsRequest
	(*ListMigrationsResponse)(nil),          // 39: atlas.v1.ListMigrationsResponse
	(*RollbackMigrationRequest)(nil),        // 40: atlas.v1.RollbackMigrationRequest
	(*RollbackMigrationResponse)(nil),       // 41: atlas.v1.RollbackMigrationResponse
	nil,                                     // 42: atlas.v1.Server.MetadataEntry
	nil,                                     // 43: atlas.v1.Character.MetadataEntry
	nil,                                     // 44: atlas.v1.GetStatsResponse.ServersByStatusEntry
	nil,                                     // 45: atlas.v1.GetStatsResponse.ServersByRegionEntry
	nil,                                     // 46: atlas.v1.GetStatsResponse.ServersByVersionEntry
}
var file_atlas_proto_depIdxs = []int32{
	0,  // 0: atlas.v1.Server.endpoint:type_name -> atlas.v1.Endpoint
	42, // 1: atlas.v1.Server.metadata:type_name -> atlas.v1.Server.MetadataEntry
	43, // 2: atlas.v1.Character.metadata:type_name -> atlas.v1.Character.MetadataEntry
	0,  // 3: atlas.v1.RegisterRequest.endpoint:type_name -> atlas.v1.Endpoint
	1,  // 4: atlas.v1.RegisterResponse.server:type_name -> atlas.v1.Server
	1,  // 5: atlas.v1.ListServersResponse.servers:type_name -> atlas.v1.Server
	1,  // 6: atlas.v1.GetServerResponse.server:type_name -> atlas.v1.Server
	2,  // 7: atlas.v1.CreateCharacterResponse.character:type_name -> atlas.v1.Character
	2,  // 8: atlas.v1.GetCharacterResponse.character:type_name -> atlas.v1.Character
	2,  // 9: atlas.v1.ListCharactersByAccountResponse.characters:type_name -> atlas.v1.Character
	2,  // 10: atlas.v1.ListCharactersByServerResponse.characters:type_name -> atlas.v1.Character
	2,  // 11: atlas.v1.UpdateCharacterResponse.character:type_name -> atlas.v1.Character
	1,  // 12: atlas.v1.RecommendResponse.server:type_name -> atlas.v1.Server
	44, // 13: atlas.v1.GetStatsResponse.servers_by_status:type_name -> atlas.v1.GetStatsResponse.ServersByStatusEntry
	45, // 14: atlas.v1.GetStatsResponse.servers_by_region:type_name -> atlas.v1.GetStatsResponse.ServersByRegionEntry
	46, // 15: atlas.v1.GetStatsResponse.servers_by_version:type_name -> atlas.v1.GetStatsResponse.ServersByVersionEntry
	2,  // 16: atlas.v1.SearchCharactersResponse.characters:type_name -> atlas.v1.Character
	33, // 17: atlas.v1.CreateMigrationResponse.migration:type_name -> atlas.v1.Migration
	33, // 18: atlas.v1.GetMigrationResponse.migration:type_name -> atlas.v1.Migration
	33, // 19: atlas.v1.ListMigrationsResponse.migrations:type_name -> atlas.v1.Migration
	33, // 20: atlas.v1.RollbackMigrationResponse.migration:type_name -> atlas.v1.Migration
	3,  // 21: atlas.v1.RegistryService.Register:input_type -> atlas.v1.RegisterRequest
	5,  // 22: atlas.v1.RegistryService.Heartbeat:input_type -> atlas.v1.HeartbeatRequest
	7,  // 23: atlas.v1.RegistryService.Unregister:input_type -> atlas.v1.UnregisterRequest
	9,  // 24: atlas.v1.DiscoveryService.ListServers:input_type -> atlas.v1.ListServersRequest
	11, // 25: atlas.v1.DiscoveryService.GetServer:input_type -> atlas.v1.GetServerRequest
	13, // 26: atlas.v1.DirectoryService.CreateCharacter:input_type -> atlas.v1.CreateCharacterRequest
	15, // 27: atlas.v1.DirectoryService.GetCharacter:input_type -> atlas.v1.GetCharacterRequest
	17, // 28: atlas.v1.DirectoryService.ListCharactersByAccount:input_type -> atlas.v1.ListCharactersByAccountRequest
	19, // 29: atlas.v1.DirectoryService.ListCharactersByServer:input_type -> atlas.v1.ListCharactersByServerRequest
	21, // 30: atlas.v1.DirectoryService.UpdateCharacter:input_type -> atlas.v1.UpdateCharacterRequest
	23, // 31: atlas.v1.DirectoryService.DeleteCharacter:input_type -> atlas.v1.DeleteCharacterRequest
	25, // 32: atlas.v1.RoutingService.Recommend:input_type -> atlas.v1.RecommendRequest
	27, // 33: atlas.v1.AdminService.SetMaintenance:input_type -> atlas.v1.ServerIdRequest
	27, // 34: atlas.v1.AdminService.SetDrain:input_type -> atlas.v1.ServerIdRequest
	27, // 35: atlas.v1.AdminService.Enable:input_type -> atlas.v1.ServerIdRequest
	27, // 36: atlas.v1.AdminService.Disable:input_type -> atlas.v1.ServerIdRequest
	29, // 37: atlas.v1.AdminService.GetStats:input_type -> atlas.v1.GetStatsRequest
	31, // 38: atlas.v1.AdminService.SearchCharacters:input_type -> atlas.v1.SearchCharactersRequest
	34, // 39: atlas.v1.AdminService.CreateMigration:input_type -> atlas.v1.CreateMigrationRequest
	36, // 40: atlas.v1.AdminService.GetMigration:input_type -> atlas.v1.GetMigrationRequest
	38, // 41: atlas.v1.AdminService.ListMigrations:input_type -> atlas.v1.ListMigrationsRequest
	40, // 42: atlas.v1.AdminService.RollbackMigration:input_type -> atlas.v1.RollbackMigrationRequest
	4,  // 43: atlas.v1.RegistryService.Register:output_type -> atlas.v1.RegisterResponse
	6,  // 44: atlas.v1.RegistryService.Heartbeat:output_type -> atlas.v1.HeartbeatResponse
	8,  // 45: atlas.v1.RegistryService.Unregister:output_type -> atlas.v1.UnregisterResponse
	10, // 46: atlas.v1.DiscoveryService.ListServers:output_type -> atlas.v1.ListServersResponse
	12, // 47: atlas.v1.DiscoveryService.GetServer:output_type -> atlas.v1.GetServerResponse
	14, // 48: atlas.v1.DirectoryService.CreateCharacter:output_type -> atlas.v1.CreateCharacterResponse
	16, // 49: atlas.v1.DirectoryService.GetCharacter:output_type -> atlas.v1.GetCharacterResponse
	18, // 50: atlas.v1.DirectoryService.ListCharactersByAccount:output_type -> atlas.v1.ListCharactersByAccountResponse
	20, // 51: atlas.v1.DirectoryService.ListCharactersByServer:output_type -> atlas.v1.ListCharactersByServerResponse
	22, // 52: atlas.v1.DirectoryService.UpdateCharacter:output_type -> atlas.v1.UpdateCharacterResponse
	24, // 53: atlas.v1.DirectoryService.DeleteCharacter:output_type -> atlas.v1.DeleteCharacterResponse
	26, // 54: atlas.v1.RoutingService.Recommend:output_type -> atlas.v1.RecommendResponse
	28, // 55: atlas.v1.AdminService.SetMaintenance:output_type -> atlas.v1.OkResponse
	28, // 56: atlas.v1.AdminService.SetDrain:output_type -> atlas.v1.OkResponse
	28, // 57: atlas.v1.AdminService.Enable:output_type -> atlas.v1.OkResponse
	28, // 58: atlas.v1.AdminService.Disable:output_type -> atlas.v1.OkResponse
	30, // 59: atlas.v1.AdminService.GetStats:output_type -> atlas.v1.GetStatsResponse
	32, // 60: atlas.v1.AdminService.SearchCharacters:output_type -> atlas.v1.SearchCharactersResponse
	35, // 61: atlas.v1.AdminService.CreateMigration:output_type -> atlas.v1.CreateMigrationResponse
	37, // 62: atlas.v1.AdminService.GetMigration:output_type -> atlas.v1.GetMigrationResponse
	39, // 63: atlas.v1.AdminService.ListMigrations:output_type -> atlas.v1.ListMigrationsResponse
	41, // 64: atlas.v1.AdminService.RollbackMigration:output_type -> atlas.v1.RollbackMigrationResponse
	43, // [43:65] is the sub-list for method output_type
	21, // [21:43] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_atlas_proto_init() }
func file_atlas_proto_init() {
	if File_atlas_proto != nil {
		return
	}
	file_atlas_proto_msgTypes[21].OneofWrappers = []any{}
	file_atlas_proto_msgTypes[31].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atlas_proto_rawDesc), len(file_atlas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   47,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_atlas_proto_goTypes,
		DependencyIndexes: file_atlas_proto_depIdxs,
		MessageInfos:      file_atlas_proto_msgTypes,
	}.Build()
	File_atlas_proto = out.File
	file_atlas_proto_goTypes = nil
	file_atlas_proto_depIdxs = nil
}
